### ISSUE TITLE
[BUG] cqlsh not launching due to: "AttributeError: module 're' has no attribute 'sre_parse'"

### ISSUE THREAD

**Issue by stinkymatt** [datastax/astra-cli#72]
**Describe the bug**

`astra db cqlsh <db-name>` fails due to an error. Astra CLI can't run cqlsh.

**To Reproduce**

run: `astra db cqlsh <db-name>` 

**Expected behavior**
It's expected that this command successfully launches cqlsh connected to <db-name>

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: MacOS w/zsh, 
- python 3.11.3

**Additional context**
full output:

`[INFO]  Cqlsh is starting, please wait for connection establishment...
Traceback (most recent call last):
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/dsecqlsh.py", line 95, in <module>
    import cqlsh  # nopep8
    ^^^^^^^^^^^^
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/cqlsh.py", line 185, in <module>
    from cqlshlib import cql3handling, pylexotron, sslhandling, cqlshhandling
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/../pylib/cqlshlib/cql3handling.py", line 19, in <module>
    from cqlshlib.cqlhandling import CqlParsingRuleSet, Hint
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/../pylib/cqlshlib/cqlhandling.py", line 23, in <module>
    from cqlshlib import pylexotron, util
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/../pylib/cqlshlib/pylexotron.py", line 342, in <module>
    class ParsingRuleSet:
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/../pylib/cqlshlib/pylexotron.py", line 343, in ParsingRuleSet
    RuleSpecScanner = SaferScanner([
                      ^^^^^^^^^^^^^^
  File "/Users/mattkennedy/.astra/cqlsh-astra/bin/../pylib/cqlshlib/saferscanner.py", line 91, in __init__
    s = re.sre_parse.State()
        ^^^^^^^^^^^^
AttributeError: module 're' has no attribute 'sre_parse'`

**Comment by clun** [comment]
Cqlsh for Astra is outdated and should be updated in next Release of DSE
- Associated to [this bug](https://issues.apache.org/jira/browse/CASSANDRA-18088)
